CREATE DATABASE WEATHER_DB;
USE DATABASE WEATHER_DB;WEATHER_DB.RAW.WEATHER_RAWWEATHER_DB.RAW.WEATHER_RAWWEATHER_DB.RAW.WEATHER_RAW
CREATE SCHEMA RAW;
USE SCHEMA RAW;
CREATE OR REPLACE TABLE WEATHER_RAW (
    DATA VARIANT
);
LIST @WEATHER_STAGE;
COPY INTO WEATHER_RAW
FROM @WEATHER_STAGE
FILE_FORMAT = (TYPE = JSON);WEATHER_DB.RAW.WEATHER_RAW
SELECT *
FROM WEATHER_RAW;
LIST @WEATHER_STAGE;
COPY INTO WEATHER_RAW
FROM @WEATHER_STAGE/weather.json
FILE_FORMAT = (TYPE = JSON)
FORCE = TRUE;
COPY INTO WEATHER_RAW
FROM @WEATHER_STAGE
FILE_FORMAT = (TYPE = JSON)
FORCE = TRUE;
SELECT DATA
FROM WEATHER_RAW;
CREATE OR REPLACE TABLE WEATHER (
    WEATHER_ID STRING,
    CITY STRING,
    TEMPERATURE FLOAT,
    HUMIDITY INTEGER,
    DESCRIPTION STRING,
    WEATHER_TIME TIMESTAMP
);
INSERT INTO WEATHER
SELECT
    value:weather_id::STRING,
    value:city::STRING,
    value:temperature::FLOAT,
    value:humidity::INTEGER,
    value:description::STRING,
    TO_TIMESTAMP_NTZ(value:time::STRING)
FROM WEATHER_RAW,
LATERAL FLATTEN(input => DATA);
SELECT * FROM WEATHER;
SELECT CURRENT_ACCOUNT();
SELECT CURRENT_WAREHOUSE();
SELECT
    CITY,
    AVG(TEMPERATURE) AS AVG_TEMP
FROM WEATHER
GROUP BY CITY; 
SELECT CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT_NAME();